import type { CardDefinition, Zone } from './types';

export const BALANCE = {
  zoneHealth: 3,
  startingSteam: 3,
  maxSteam: 6,
  steamIntervalMs: 900,
  handSize: 4,
  refillDelayMs: 700,
  recycleDelayMs: 1_200,
  specialDisplayMs: 600,
  announcementMs: 900,
  returnFuseMs: 1_500,
  hasteMs: 600,
  hasteMinimumMs: 300,
  minFlickDistance: 28,
  minTravelMs: 180,
  maxTravelMs: 350,
} as const;

export const ZONE_LABELS: Record<Zone, string> = {
  kopf: 'Kopf',
  bauch: 'Bauch',
  beine: 'Beine',
};

export const ZONE_SYMBOLS: Record<Zone, string> = {
  kopf: '▲',
  bauch: '●',
  beine: '║',
};

export const CARD_DEFINITIONS = [
  {
    id: 'kopfnuss',
    name: 'Kopfnuss',
    shortName: 'Nuss',
    kind: 'attack',
    cost: 2,
    copies: 3,
    zone: 'kopf',
    durationMs: 1_800,
    damage: 1,
    description: '1 Treffer gegen den Kopf.',
  },
  {
    id: 'bauchklatscher',
    name: 'Bauchklatscher',
    shortName: 'Klatsch',
    kind: 'attack',
    cost: 2,
    copies: 3,
    zone: 'bauch',
    durationMs: 1_600,
    damage: 1,
    description: '1 Treffer gegen den Bauch.',
  },
  {
    id: 'schienbein',
    name: 'Schienbein-Schreck',
    shortName: 'Aua!',
    kind: 'attack',
    cost: 2,
    copies: 3,
    zone: 'beine',
    durationMs: 1_400,
    damage: 1,
    description: '1 schneller Treffer gegen die Beine.',
  },
  {
    id: 'doppelwumms',
    name: 'Doppelwumms',
    shortName: 'WUMMS',
    kind: 'attack',
    cost: 4,
    copies: 1,
    zone: 'choice',
    durationMs: 2_600,
    damage: 2,
    description: 'Wähle eine Zone. 2 Treffer mit langer Warnung.',
  },
  {
    id: 'dickschaedel',
    name: 'Dickschädel',
    shortName: 'Dickkopf',
    kind: 'guard',
    cost: 1,
    copies: 2,
    zone: 'kopf',
    durationMs: 3_000,
    description: 'Fängt den nächsten Kopfangriff.',
  },
  {
    id: 'bauch-rein',
    name: 'Bauch rein!',
    shortName: 'Einziehen',
    kind: 'guard',
    cost: 1,
    copies: 2,
    zone: 'bauch',
    durationMs: 2_800,
    description: 'Fängt den nächsten Bauchangriff.',
  },
  {
    id: 'hopser',
    name: 'Hopser',
    shortName: 'Hops!',
    kind: 'guard',
    cost: 1,
    copies: 2,
    zone: 'beine',
    durationMs: 2_400,
    description: 'Fängt den nächsten Beinangriff.',
  },
  {
    id: 'retourkutsche',
    name: 'Retourkutsche',
    shortName: 'Retour',
    kind: 'special',
    cost: 3,
    copies: 2,
    zone: 'choice',
    durationMs: 600,
    effect: 'counter',
    description: 'Kontert den ältesten Angriff in einer Zone.',
  },
  {
    id: 'ablenkung',
    name: 'Ablenkungsmanöver',
    shortName: 'Ablenken',
    kind: 'special',
    cost: 2,
    copies: 1,
    zone: 'choice',
    durationMs: 600,
    effect: 'redirect',
    description: 'Schiebt einen Angriff in die nächste gesunde Zone.',
  },
  {
    id: 'jetzt-erst-recht',
    name: 'Jetzt erst recht!',
    shortName: 'Zack!',
    kind: 'special',
    cost: 2,
    copies: 1,
    zone: 'none',
    durationMs: 600,
    effect: 'haste',
    description: 'Eigene Angriffe werden 0,6 Sekunden schneller.',
  },
  {
    id: 'retour-angriff',
    name: 'Zurück damit!',
    shortName: 'Retour!',
    kind: 'attack',
    cost: 0,
    copies: 0,
    zone: 'choice',
    durationMs: 1_500,
    damage: 1,
    description: 'Der zurückgeschickte Konter.',
  },
] as const satisfies readonly CardDefinition[];

export const CARD_BY_ID: ReadonlyMap<string, CardDefinition> = new Map(
  CARD_DEFINITIONS.map((card) => [card.id, card]),
);
