import type { CardDefinition, Zone } from './model';

export const BALANCE = {
  zoneHealth: 3,
  startingTokens: 3,
  maxTokens: 6,
  tokenIntervalMs: 1_200,
  handSize: 4,
  refillDelayMs: 900,
  announcementMs: 1_100,
  minFlickDistance: 28,
  minTravelMs: 220,
  maxTravelMs: 480,
} as const;

export const ZONE_LABELS: Record<Zone, string> = {
  kontext: 'Kontext',
  logik: 'Logik',
  output: 'Ausgabe',
};

export const ZONE_SYMBOLS: Record<Zone, string> = {
  kontext: '▣',
  logik: '⌘',
  output: '›_',
};

export const CARD_DEFINITIONS = [
  {
    id: 'kontext-kollaps',
    name: 'Kontextzertrümmerungshammer',
    shortName: 'Kontext-Hammer',
    kind: 'attack',
    cost: 2,
    copies: 3,
    zone: 'kontext',
    durationMs: 2_700,
    damage: 1,
    description: '1 Treffer gegen den Kontext.',
  },
  {
    id: 'denkfehler',
    name: 'Logikverdrehungsmaschine',
    shortName: 'Logikverdreher',
    kind: 'attack',
    cost: 2,
    copies: 3,
    zone: 'logik',
    durationMs: 2_400,
    damage: 1,
    description: '1 Treffer gegen die Logik.',
  },
  {
    id: 'output-salat',
    name: 'Ausgabeverwüstungskanone',
    shortName: 'Ausgabekanone',
    kind: 'attack',
    cost: 2,
    copies: 3,
    zone: 'output',
    durationMs: 2_100,
    damage: 1,
    description: '1 Treffer gegen die Ausgabe.',
  },
  {
    id: 'tokensturm',
    name: 'Rechenleistungsüberlastungsgewitter',
    shortName: 'Überlastungsgewitter',
    kind: 'attack',
    cost: 4,
    copies: 2,
    zone: 'choice',
    durationMs: 3_900,
    damage: 2,
    description: 'Wähle eine Zone. 2 Treffer mit langer Vorwarnung.',
  },
  {
    id: 'kontext-puffer',
    name: 'Kontextzusammenprallschutzpolster',
    shortName: 'Kontextpolster',
    kind: 'guard',
    cost: 1,
    copies: 3,
    zone: 'kontext',
    durationMs: 4_200,
    description: 'Fängt den nächsten Kontext-Angriff.',
  },
  {
    id: 'plausi-check',
    name: 'Logikfehlerabwehrschild',
    shortName: 'Logikschild',
    kind: 'guard',
    cost: 1,
    copies: 3,
    zone: 'logik',
    durationMs: 3_900,
    description: 'Fängt den nächsten Logik-Angriff.',
  },
  {
    id: 'output-filter',
    name: 'Ausgabeschadensbegrenzungsfilter',
    shortName: 'Ausgabefilter',
    kind: 'guard',
    cost: 1,
    copies: 3,
    zone: 'output',
    durationMs: 3_600,
    description: 'Fängt den nächsten Ausgabe-Angriff.',
  },
  {
    id: 'bundes-guardrail',
    name: 'Bundesrundumverteidigungszaun',
    shortName: 'Bundeswehrzaun',
    kind: 'guard',
    cost: 2,
    copies: 2,
    zone: 'choice',
    durationMs: 3_000,
    description: 'Wähle eine beliebige Zone und blocke dort.',
  },
] as const satisfies readonly CardDefinition[];

export const CARD_BY_ID: ReadonlyMap<string, CardDefinition> = new Map(
  CARD_DEFINITIONS.map((card) => [card.id, card]),
);
